Visual Studio Code (1.93.0, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.1.
Pylance Extension Version: 2024.10.1.
Platform: linux (x64).
Temp Storage folder ~/.config/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.1
Workspace folder ~/hse/machine_learning, Home = /home/yoshee
22:08:01.230 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.6) for '~/hse/machine_learning/sem_6_classwork.ipynb' (disableUI=true)
22:08:01.247 [warn] Failed to get activated env vars for /bin/python3 in 19ms
22:08:01.249 [warn] Failed to get activated env vars for /bin/python3 in 12ms
22:08:01.256 [info] Process Execution: /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
22:08:01.264 [warn] Failed to get activated env vars for /bin/python3 in 3ms
22:08:01.276 [info] Process Execution: /bin/python3 -m pip list
22:08:01.281 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
22:08:01.287 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v37768d33f78cbfe2190fbbcd0c1bbd9dd1c6b33de.json
    > cwd: //home/~/hse/machine_learning
22:08:01.296 [info] Process Execution: /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
22:08:02.137 [info] Kernel successfully started
22:08:03.617 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.6) for '~/hse/machine_learning/sem_7_classwork.ipynb' (disableUI=true)
22:08:03.649 [warn] Failed to get activated env vars for /bin/python3 in 30ms
22:08:03.657 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
22:08:03.667 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v3d57edcbcf056939eae9b0956fe518c9d6e6ebda9.json
    > cwd: //home/~/hse/machine_learning
22:08:04.301 [info] Kernel successfully started
22:08:04.314 [info] Process Execution: /bin/python3 /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/pythonFiles/printJupyterDataDir.py
22:08:19.396 [info] Dispose Kernel '~/hse/machine_learning/sem_6_classwork.ipynb' associated with '~/hse/machine_learning/sem_6_classwork.ipynb'
22:08:19.403 [info] Dispose Kernel '~/hse/machine_learning/sem_7_classwork.ipynb' associated with '~/hse/machine_learning/sem_7_classwork.ipynb'
22:08:19.432 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v3d57edcbcf056939eae9b0956fe518c9d6e6ebda9.json for pid 3135 Canceled (FileSystemError): Canceled
    at Function.e (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:7311)
    at Object.stat (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3977)
    at Jc.delete (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:239:15273)
    at /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
22:08:19.433 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v37768d33f78cbfe2190fbbcd0c1bbd9dd1c6b33de.json for pid 3051 Canceled (FileSystemError): Canceled
    at Function.e (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:7311)
    at Object.stat (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3977)
    at Jc.delete (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:239:15273)
    at /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
